[package]
name = "codegen"
version = "0.1.0"
edition = "2021"

[dependencies]
Inflector = "0.11.4"
chrono = { version = "0.4.38", features = ["serde"] }
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
ssdp-client = "2.0.0"
