name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: "Install Rust"
      uses: dtolnay/rust-toolchain@nightly
      with:
        components: rustfmt
    - name: Codegen
      run: |
        source $HOME/.cargo/env
        cd codegen ; cargo run
        cargo +nightly fmt
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test

